micronaut:
  application:
    name: trendingHashtagMicroservice
datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:`db-trendingHashtags`}/${DB_NAME:trendingHashtags}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.trendingHashtags.domain
    properties:
      hibernate:
        show_sql: ${DEBUG_SQL:false}
        format_sql: ${DEBUG_SQL:false}
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`kafka-0:9094`}
